[tool.poetry]
name = "codeboxapi"
version = "0.0.16"
authors = ["Shroominic <contact@shroominic.com>"]
license = "MIT"
description = "CodeBox is a sandboxed python environment for your LLM Agents."
keywords = ["codebox", "api", "cloud", "cloud-infra", "llm", "apps", "codeinterpreterapi"]
readme = "README.md"
homepage = "https://codeboxapi.com/"
documentation = "https://codeboxapi.com/docs"
repository = "https://github.com/shroominic/codebox-api"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1"
requests = "^2.27"
aiohttp = "^3.8"
websockets = "^11"
python-dotenv = "^1"
jupyter-kernel-gateway = { version = "^2", optional = true }
Pillow = { version = "^9", optional = true }

[tool.poetry.extras]
all = ["jupyter-kernel-gateway", "Pillow"]
local_support = ["jupyter-kernel-gateway"]
image_support = ["Pillow"]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^7"
mypy = "^1.4"
black = "^23"
flake8 = "^6"
pre-commit = "^3"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
