name: pre-commit

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pre-commit
      run: pip install pre-commit pytest
    - name: Run pre-commit
      run: pre-commit run --all-files
    - name: Run tests
      run: pytest
